spring:
  application:
    name: poctime

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/poctime-app
          jwk-set-uri: http://localhost:9090/realms/poctime-app/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/poctime
    username: admin
    password: admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin@123
    virtual-host: poctime

  cloud:
    stream:
      bindings:
        exchangePerson-out-0:
          destination: exchange.person
          content-type: application/json
        exchangeOrganization-out-0:
          destination: exchange.organization
          content-type: application/json
      rabbit:
        bindings:
          exchangePerson-out-0:
            producer:
              routing-key-expression: "''"
              exchangeType: headers
              declare-exchange: true
          exchangeOrganization-out-0:
            producer:
              routing-key-expression: "''"
              exchangeType: headers
              declare-exchange: true

server:
  port: 8181